# Generated by Django 5.1.7 on 2025-09-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
