# Generated by Django 5.1.7 on 2025-09-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_document_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
