# Generated by Django 5.1.7 on 2025-09-26 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_document_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AlterField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
